# ============================================================================
# ABC-SMC inference for `fiber` — time-varying scenario version
# ----------------------------------------------------------------------------
# Inferential targets (3 parameters):
#   1. R0                          : baseline reproduction number for a typical
#                                    genPop seeding case (evaluated at t = 0
#                                    using the scenario's unsafe-funeral prob)
#   2. prop_funeral                : share of R0 attributable to funeral
#                                    transmission at t = 0
#   3. prob_hcw_cond_genPop_hospital : probability that a hospital-located
#                                      infection generated by a genPop parent
#                                      is an HCW
#
# Fitted to 3 observed summaries (+ a takeoff indicator to handle bimodality):
#   - total deaths
#   - total HCW deaths
#   - outbreak duration (first death -> last outcome, in days)
#
# Strategy:
#   At each theta, run N replicates. A replicate "took off" if it produced
#   >= TAKEOFF_DEATH_THRESHOLD deaths. We report P(takeoff) plus the mean of
#   each conditional summary among replicates that took off; if zero replicates
#   take off, summaries return zeros so the distance to observed is large.
#
# Prerequisites in the working directory:
#   - 00_common_time_varying_scenario_setup.R  (sourced; provides defaults,
#     make_base_args, build_time_varying_args, time-varying machinery, and
#     also sources model_functions/ for the package code)
#   - final_four_scenario_values.csv           (scenario trajectory matrix)
#   - model_functions/                         (folder with package R files)
# ============================================================================
library(EasyABC)
library(future)
library(future.apply)
library(parallel)
library(progressr)
handlers("progress")   # nice text progress bar with ETA

PACKAGE_ROOT <- switch(
  Sys.info()[["user"]],
  "cwhittaker" = "C:/Users/cwhittaker/Documents/Research Projects/fiber",
  "PETAL_WS_2" = "C:/Users/PETAL_WS_2/Documents/fiber",
  stop("Unknown user — add this machine.")
)
ABC_DIR <- file.path(PACKAGE_ROOT, "inst", "charlie_abc_attempt")
setwd(PACKAGE_ROOT)

source(file.path(ABC_DIR, "00_common_time_varying_scenario_setup.R"))
source(file.path(ABC_DIR, "calculate_model_approx_R0.R"))

# ---- Cluster setup (run ONCE; reuse for all parallel work) ------------------

# N_WORKERS <- 10
# cl <- makeCluster(N_WORKERS)
# clusterExport(cl, c("PACKAGE_ROOT", "ABC_DIR"))
#
# # One-time sourcing on each worker.
# clusterEvalQ(cl, {
#   setwd(PACKAGE_ROOT)   # so SCRIPT_DIR in the setup file resolves to <root>/R/
#   source(file.path(ABC_DIR, "00_common_time_varying_scenario_setup.R"))
#   source(file.path(ABC_DIR, "calculate_model_approx_R0.R"))
# })
#
#
# # Tell future to dispatch to this cluster.
# plan(cluster, workers = cl)

# ============================================================================
# 1. SOURCE THE COMMON SETUP
#    Brings in DEFAULT_SCALAR_INPUTS, make_base_args(),
#    build_time_varying_args(), make_gamma_sampler(), and all model functions.
# ============================================================================
source("inst/charlie_abc_attempt/00_common_time_varying_scenario_setup.R")
source("inst/charlie_abc_attempt/calculate_model_approx_R0.R")

# ============================================================================
# 2. CHOOSE SCENARIO + BUILD FIXED ARGS
#    These do not depend on theta and are computed once.
# ============================================================================

SCENARIO_ID  <- "Worst_WestAfrica"
SCENARIO_CSV <- "inst/charlie_abc_attempt/final_four_scenario_values.csv"
scenario_matrix <- read_scenario_matrix(SCENARIO_CSV)

base_args <- make_base_args(scalar_inputs = DEFAULT_SCALAR_INPUTS)

tv_args <- build_time_varying_args(
  scenario_id           = SCENARIO_ID,
  matrix                = scenario_matrix,
  etu_efficacy_baseline = DEFAULT_SCALAR_INPUTS$etu_efficacy_baseline
)

plot(scenario_matrix$relative_day[scenario_matrix$scenario_label == "Worst_WestAfrica"],
     scenario_matrix$prob_hosp[scenario_matrix$scenario_label == "Worst_WestAfrica"])

scenario_label <- tv_args$scenario_label
tv_args_model  <- tv_args[setdiff(names(tv_args), c("scenario_label", "scenario_matrix"))]

# Compute the direct (D) and funeral (F) R0-multipliers at t = 0 ONCE.
# These depend only on fixed scenario inputs at t = 0, not on the 3 fitted
# parameters, so we can divide by them inside build_model_args.
# R0 = 1 and prop_funeral = 0.5 are dummies; only D and F are extracted.
setup_solve <- solve_offspring_means_for_R0(
  R0                                    = 1.0,
  args                                  = c(base_args, tv_args_model),
  proportion_transmission_from_funerals = 0.5,
  n                                     = 100000,    # tight MC noise for one-off cost
  seed                                  = 42
)
D_direct_multiplier  <- setup_solve$D_direct_multiplier
F_funeral_multiplier <- setup_solve$F_funeral_multiplier

base_args$check_final_size <- 30000

# ============================================================================
# 3. PARAMETER CONVERSION
#    (R0, prop_funeral, p_hcw) -> override the three relevant fiber inputs.
#    mn_offspring_hcw is FIXED (from DEFAULT_SCALAR_INPUTS), not derived.
# ============================================================================
### Note the arbitrary choice of seeding cases, something we need to be wary of
build_model_args <- function(R0, prop_funeral, hcw_risk_scalar,
                             base = base_args, tv = tv_args_model,
                             seeding_cases = 25,
                             D = D_direct_multiplier,
                             F_fun = F_funeral_multiplier) {

  mn_genPop  <- (1 - prop_funeral) * R0 / D
  mn_funeral <-      prop_funeral  * R0 / F_fun

  args <- c(base, tv)
  args$mn_offspring_genPop           <- mn_genPop
  args$mn_offspring_funeral          <- mn_funeral

  # Scale BOTH HCW-hospital probabilities by the same multiplier, capped at 1
  args$prob_hcw_cond_genPop_hospital <- pmin(
    DEFAULT_SCALAR_INPUTS$prob_hcw_cond_genPop_hospital * hcw_risk_scalar, 1.0)
  args$prob_hcw_cond_hcw_hospital    <- pmin(
    DEFAULT_SCALAR_INPUTS$prob_hcw_cond_hcw_hospital    * hcw_risk_scalar, 1.0)

  args$seed                          <- NULL
  args$seeding_cases                 <- seeding_cases
  args
}

x <- build_model_args(R0 = 1.7, prop_funeral = 0.25,
                      hcw_risk_scalar = 2.0,
                      base = base_args, tv = tv_args_model)

x$mn_offspring_genPop
x$mn_offspring_funeral
x$prob_hcw_cond_genPop_hospital
x$prob_hcw_cond_hcw_hospital

# ============================================================================
# 4. SUMMARY FUNCTION
#    First-death-based: takeoff requires >= K deaths; duration measured from
#    first death to last outcome.
# ============================================================================

TAKEOFF_DEATH_THRESHOLD <- 100   # raise/lower to tune what counts as "took off"

# note abc_summarise moved to 00_common_time_varying... so it can be picked up by parallel abc function


# ============================================================================
# 5. SINGLE-REPLICATE RUNNER + ABC MODEL WRAPPER
# ============================================================================

run_one_sim <- function(args) {
  out <- do.call(branching_process_main, args)
  abc_summarise(out)
}

fiber_abc_model <- function(theta,
                            n_replicates    = N_REPLICATES,
                            include_n_cases = FALSE) {

  R0              <- theta[1]
  prop_funeral    <- theta[2]
  hcw_risk_scalar <- theta[3]

  args <- build_model_args(R0, prop_funeral, hcw_risk_scalar)

  reps <- vapply(seq_len(n_replicates),
                 function(i) run_one_sim(args), numeric(4))

  took_off     <- reps["n_deaths", ] >= TAKEOFF_DEATH_THRESHOLD
  takeoff_frac <- mean(took_off)

  if (!any(took_off)) {
    out <- c(takeoff = 0, n_deaths = 0, n_hcw_deaths = 0, duration = 0)
    if (include_n_cases) out <- c(out, n_cases = 0)
    return(out)
  }

  out <- c(takeoff      = takeoff_frac,
           n_deaths     = mean(reps["n_deaths",     took_off]),
           n_hcw_deaths = mean(reps["n_hcw_deaths", took_off]),
           duration     = mean(reps["duration",     took_off]))

  if (include_n_cases) {
    out <- c(out, n_cases = mean(reps["n_cases", took_off]))
  }

  out
}


# ============================================================================
# 6. OBSERVED SUMMARIES (edit to match your real outbreak)
# ============================================================================

observed_summaries <- c(
  takeoff      = 1.0,    # observed outbreak did take off (>= 10 deaths)
  n_deaths     = 11325,
  n_hcw_deaths = 513,
  duration     = 365 # lots of spatial heterogeneity sustained it, but main outbreak was about a year total
)

# ============================================================================
# 7. PRIORS
# ============================================================================

priors <- list(
  c("unif", 1.35,  1.55),  # R0
  c("unif", 0.1,  0.4),    # prop_funeral
  c("unif", 1, 2.5)    # prob_hcw_cond_genPop_hospital
)

# ============================================================================
# 8. PRIOR PREDICTIVE CHECK -- RUN THIS FIRST
# ============================================================================

prior_predictive_check <- function(n_draws         = 20,
                                   prior_list      = priors,
                                   param_names     = c("R0", "prop_funeral", "hcw_risk_scalar"),
                                   parallel        = TRUE,
                                   n_replicates    = N_REPLICATES,
                                   include_n_cases = TRUE) {       # NEW

  sample_one <- function(spec, n) {
    dist   <- spec[1]
    params <- as.numeric(spec[-1])
    switch(dist,
           "unif"        = runif(n,  min = params[1], max = params[2]),
           "normal"      = rnorm(n,  mean = params[1], sd = params[2]),
           "lognormal"   = rlnorm(n, meanlog = params[1], sdlog = params[2]),
           "exponential" = rexp(n,   rate = params[1]),
           stop("Unsupported prior distribution: ", dist)
    )
  }

  draws <- as.data.frame(lapply(prior_list, sample_one, n = n_draws))
  names(draws) <- param_names

  theta_list <- lapply(seq_len(nrow(draws)), function(i) as.numeric(draws[i, ]))

  sims_list <- with_progress({
    p <- progressor(steps = length(theta_list))

    fn <- function(theta) {
      out <- fiber_abc_model(theta,
                             n_replicates    = n_replicates,
                             include_n_cases = include_n_cases)
      p()
      out
    }

    if (parallel) {
      future_lapply(theta_list, fn, future.seed = TRUE)
    } else {
      lapply(theta_list, fn)
    }
  })

  sims <- do.call(rbind, sims_list)
  cbind(draws, as.data.frame(sims))
}

# set.seed(1)
# system.time(pp_par <- prior_predictive_check(20, parallel = TRUE, n_replicates = 5))
# set.seed(1)
# system.time(pp_ser <- prior_predictive_check(20, parallel = FALSE, n_replicates = 5))

# parallel::stopCluster(cl)
# future::plan(sequential)
# rm(cl)
# gc()

# prior_predictive_check(n_draws = 1000, prior_list = priors)
# set.seed(1)
# pp <- prior_predictive_check(20)
# print(pp)
# summary(pp)


# ============================================================================
# 9. RUN ABC-SMC (Del Moral et al. 2012 adaptive algorithm)
# ============================================================================

fiber_abc_model_parallel <- function(theta_with_seed) {

  # ---- Worker self-bootstrap (runs once per worker on first call) ----
  if (!exists(".fiber_worker_ready", envir = globalenv(), inherits = FALSE)) {

    # ---- Per-machine paths ----
    PACKAGE_ROOT <- switch(
      Sys.info()[["user"]],
      "cwhittaker" = "C:/Users/cwhittaker/Documents/Research Projects/fiber",
      "PETAL_WS_2" = "C:/Users/PETAL_WS_2/Documents/fiber",
      stop("Unknown user: ", Sys.info()[["user"]],
           ". Add this machine to the PACKAGE_ROOT switch.")
    )

    ABC_DIR      <- file.path(PACKAGE_ROOT, "inst", "charlie_abc_attempt")
    SETUP_PATH   <- file.path(ABC_DIR, "00_common_time_varying_scenario_setup.R")
    R0_PATH      <- file.path(ABC_DIR, "calculate_model_approx_R0.R")
    SCENARIO_CSV <- file.path(ABC_DIR, "final_four_scenario_values.csv")
    SCENARIO_ID  <- "Worst_WestAfrica"

    setwd(PACKAGE_ROOT)
    source(SETUP_PATH)
    source(R0_PATH)

    scenario_matrix <- read_scenario_matrix(SCENARIO_CSV)
    base_args <- make_base_args(scalar_inputs = DEFAULT_SCALAR_INPUTS)
    base_args$check_final_size <- 30000

    tv_args <- build_time_varying_args(
      scenario_id           = SCENARIO_ID,
      matrix                = scenario_matrix,
      etu_efficacy_baseline = DEFAULT_SCALAR_INPUTS$etu_efficacy_baseline
    )
    tv_args_model <- tv_args[setdiff(names(tv_args),
                                     c("scenario_label", "scenario_matrix"))]

    setup_solve <- solve_offspring_means_for_R0(
      R0   = 1.0,
      args = c(base_args, tv_args_model),
      proportion_transmission_from_funerals = 0.5,
      n    = 100000,
      seed = 42
    )

    # Stash everything in globalenv so subsequent calls find them
    assign("base_args",               base_args,                          envir = globalenv())
    assign("tv_args_model",           tv_args_model,                      envir = globalenv())
    assign("D_direct_multiplier",     setup_solve$D_direct_multiplier,    envir = globalenv())
    assign("F_funeral_multiplier",    setup_solve$F_funeral_multiplier,   envir = globalenv())
    assign("TAKEOFF_DEATH_THRESHOLD", 100,                                envir = globalenv())
    assign(".fiber_worker_ready",     TRUE,                               envir = globalenv())
  }

  # ---- Per-call logic ----
  # First element is the seed (because use_seed = TRUE)
  set.seed(theta_with_seed[1])

  R0           <- theta_with_seed[2]
  prop_funeral <- theta_with_seed[3]
  hcw_risk_scalar <- theta_with_seed[4]

  mn_genPop  <- (1 - prop_funeral) * R0 / D_direct_multiplier
  mn_funeral <-      prop_funeral  * R0 / F_funeral_multiplier

  args <- c(base_args, tv_args_model)
  args$mn_offspring_genPop           <- mn_genPop
  args$mn_offspring_funeral          <- mn_funeral
  args$prob_hcw_cond_genPop_hospital <- pmin(DEFAULT_SCALAR_INPUTS$prob_hcw_cond_genPop_hospital * hcw_risk_scalar, 1.0)
  args$prob_hcw_cond_hcw_hospital    <- pmin(DEFAULT_SCALAR_INPUTS$prob_hcw_cond_hcw_hospital    * hcw_risk_scalar, 1.0)
  args$seed                          <- NULL
  args$seeding_cases                 <- 25

  N_REPS <- 20 ## NEED TO CHANGE THIS SO IT'S NOT HARD CODED
  reps <- vapply(seq_len(N_REPS), function(i) {
    out <- do.call(branching_process_main, args)
    abc_summarise(out)
  }, numeric(4))
  rownames(reps) <- c("n_cases", "n_deaths", "n_hcw_deaths", "duration")

  took_off <- reps["n_deaths", ] >= TAKEOFF_DEATH_THRESHOLD
  if (!any(took_off)) {
    return(c(takeoff = 0, n_deaths = 0, n_hcw_deaths = 0, duration = 0))
  }
  c(takeoff      = mean(took_off),
    n_deaths     = mean(reps["n_deaths",     took_off]),
    n_hcw_deaths = mean(reps["n_hcw_deaths", took_off]),
    duration     = mean(reps["duration",     took_off]))
}

# N_REPLICATES <- 5   ## NEED TO CHANGE CURRENTLY AS THIS IS DOING NOTHING AND IT'S HARD CODED ABOVE
if (grepl("PETAL", Sys.info()[["user"]], ignore.case = TRUE)) {
  n_cluster <- min(110, parallel::detectCores() - 10)
} else {
  n_cluster <- min(10,  parallel::detectCores() - 4)
}

start_time <- Sys.time()
result <- ABC_sequential(
  method              = "Delmoral",
  model               = fiber_abc_model_parallel,
  prior               = priors,
  nb_simul            = 200,
  summary_stat_target = observed_summaries,
  alpha               = 0.5,
  tolerance_target    = 0.5,
  M                   = 1,
  use_seed            = TRUE,
  verbose             = TRUE,
  n_cluster           = n_cluster
)
end_time <- Sys.time()
print(end_time - start_time)

# ============================================================================
# 10. POSTERIOR INSPECTION
# ============================================================================

posterior <- as.data.frame(result$param)
colnames(posterior) <- c("R0", "prop_funeral", "hcw_risk_scalar")

print(apply(posterior, 2, quantile, probs = c(0.025, 0.5, 0.975)))

par(mfrow = c(1, 3))
for (j in seq_len(ncol(posterior))) {
  hist(posterior[, j], breaks = 15, main = colnames(posterior)[j],
       xlab = colnames(posterior)[j])
  abline(v = quantile(posterior[, j], c(0.025, 0.5, 0.975)),
         lty = c(2, 1, 2), col = "red")
}
par(mfrow = c(1, 1))

pairs(posterior, pch = 16, cex = 0.5,
      col = adjustcolor("steelblue", alpha = 0.4))

saveRDS(result,
        file = paste0("fiber_abc_smc_result_", SCENARIO_ID, "_phase2.rds"))

# Move Phase 1 outputs out of the way (run this before launching Phase 2)
# dir.create(file.path(PACKAGE_ROOT, "phase1_outputs"), showWarnings = FALSE)
# files_to_move <- list.files(PACKAGE_ROOT,
#                             pattern = "^(output_step|tolerance_step|n_simul_tot_step)[0-9]+$",
#                             full.names = TRUE)
# file.rename(files_to_move,
#             file.path(PACKAGE_ROOT, "phase1_outputs", basename(files_to_move)))
# file.rename(file.path(PACKAGE_ROOT, "fiber_abc_smc_result_Worst_WestAfrica.rds"),
#             file.path(PACKAGE_ROOT, "fiber_abc_smc_result_Worst_WestAfrica_phase1.rds"))
