# ============================================================================
# ABC-SMC inference for `fiber` — time-varying scenario version
# ----------------------------------------------------------------------------
# Inferential targets (3 parameters):
#   1. R0                          : baseline reproduction number for a typical
#                                    genPop seeding case (evaluated at t = 0
#                                    using the scenario's unsafe-funeral prob)
#   2. prop_funeral                : share of R0 attributable to funeral
#                                    transmission at t = 0
#   3. prob_hcw_cond_genPop_comm   : probability that a community infection
#                                    generated by a genPop parent is an HCW
#
# Fitted to 3 observed summaries (+ a takeoff indicator to handle bimodality):
#   - total deaths
#   - total HCW deaths
#   - outbreak duration (first death -> last outcome, in days)
#
# Strategy:
#   At each theta, run N replicates. A replicate "took off" if it produced
#   >= TAKEOFF_DEATH_THRESHOLD deaths. We report P(takeoff) plus the mean of
#   each conditional summary among replicates that took off; if zero replicates
#   take off, summaries return zeros so the distance to observed is large.
#
# Prerequisites in the working directory:
#   - 00_common_time_varying_scenario_setup.R  (sourced; provides defaults,
#     make_base_args, build_time_varying_args, time-varying machinery, and
#     also sources model_functions/ for the package code)
#   - final_four_scenario_values.csv           (scenario trajectory matrix)
#   - model_functions/                         (folder with package R files)
# ============================================================================
library(EasyABC)
library(future)
library(future.apply)
library(parallel)
library(progressr)
handlers("progress")   # nice text progress bar with ETA

# ---- Cluster setup (run ONCE; reuse for all parallel work) ------------------

N_WORKERS <- 10
cl <- makeCluster(N_WORKERS)

# One-time sourcing on each worker.
clusterEvalQ(cl, source("C:/Users/cwhittaker/Documents/Research Projects/fiber/inst/charlie_abc_attempt/00_common_time_varying_scenario_setup.R"))

# Tell future to dispatch to this cluster.
plan(cluster, workers = cl)

# ============================================================================
# 1. SOURCE THE COMMON SETUP
#    Brings in DEFAULT_SCALAR_INPUTS, make_base_args(),
#    build_time_varying_args(), make_gamma_sampler(), and all model functions.
# ============================================================================
source("inst/charlie_abc_attempt/00_common_time_varying_scenario_setup.R")

# ============================================================================
# 2. CHOOSE SCENARIO + BUILD FIXED ARGS
#    These do not depend on theta and are computed once.
# ============================================================================

SCENARIO_ID  <- "Worst_WestAfrica"
SCENARIO_CSV <- "C:/Users/cwhittaker/Documents/Research Projects/fiber/inst/charlie_abc_attempt/final_four_scenario_values.csv"
scenario_matrix <- read_scenario_matrix(SCENARIO_CSV)

base_args <- make_base_args(scalar_inputs = DEFAULT_SCALAR_INPUTS)

tv_args <- build_time_varying_args(
  scenario_id           = SCENARIO_ID,
  matrix                = scenario_matrix,
  etu_efficacy_baseline = DEFAULT_SCALAR_INPUTS$etu_efficacy_baseline
)

scenario_label <- tv_args$scenario_label
tv_args_model  <- tv_args[setdiff(names(tv_args), c("scenario_label", "scenario_matrix"))]

# Evaluate the time-varying unsafe-funeral-in-community probability at t = 0.
# This is the conversion constant for the R0 -> mn_offspring_funeral mapping.
p_unsafe_funeral_comm_t0 <- tv_args_model$p_unsafe_funeral_comm_genPop(0)
prob_death_comm_fixed    <- base_args$prob_death_comm

cat(sprintf(
  "Scenario: %s (%s)\n  p_unsafe_funeral_comm_genPop(0) = %.3f\n  prob_death_comm = %.3f\n",
  SCENARIO_ID, scenario_label, p_unsafe_funeral_comm_t0, prob_death_comm_fixed
))

base_args$check_final_size <- 25000

# ============================================================================
# 3. PARAMETER CONVERSION
#    (R0, prop_funeral, p_hcw) -> override the three relevant fiber inputs.
#    mn_offspring_hcw is FIXED (from DEFAULT_SCALAR_INPUTS), not derived.
# ============================================================================

build_model_args <- function(R0, prop_funeral, prob_hcw_cond_genPop_comm,
                             base = base_args, tv = tv_args_model) {

  mn_genPop  <- R0 * (1 - prop_funeral)
  mn_funeral <- R0 * prop_funeral / (prob_death_comm_fixed * p_unsafe_funeral_comm_t0)

  args <- c(base, tv)
  args$mn_offspring_genPop       <- mn_genPop
  args$mn_offspring_funeral      <- mn_funeral
  args$prob_hcw_cond_genPop_comm <- prob_hcw_cond_genPop_comm
  # mn_offspring_hcw left at the fixed default (e.g. 0.20)
  args$seed <- NULL
  args
}

x <- build_model_args(R0 = 1.5, prop_funeral = 0.35, prob_hcw_cond_genPop_comm = 0.02, base = base_args, tv = tv_args_model)
x$mn_offspring_genPop
x$mn_offspring_funeral

# ============================================================================
# 4. SUMMARY FUNCTION
#    First-death-based: takeoff requires >= K deaths; duration measured from
#    first death to last outcome.
# ============================================================================

TAKEOFF_DEATH_THRESHOLD <- 100   # raise/lower to tune what counts as "took off"

abc_summarise <- function(out) {
  tdf <- out$tdf
  tdf <- tdf[!is.na(tdf$time_infection_absolute), , drop = FALSE]

  if (nrow(tdf) == 0L) {
    return(c(n_deaths = 0, n_hcw_deaths = 0, duration = 0))
  }

  deaths <- !is.na(tdf$outcome) & tdf$outcome
  hcw    <- !is.na(tdf$class) & tdf$class == "HCW"

  n_cases      <- nrow(tdf)
  n_deaths     <- sum(deaths)
  n_hcw_deaths <- sum(deaths & hcw)

  if (n_deaths == 0L) {
    duration <- 0
  } else {
    t_first_death <- min(tdf$time_outcome_absolute[deaths], na.rm = TRUE)
    t_last_event  <- max(tdf$time_outcome_absolute,         na.rm = TRUE)
    duration      <- max(t_last_event - t_first_death, 0)
  }

  c(n_cases = n_cases, n_deaths = n_deaths, n_hcw_deaths = n_hcw_deaths, duration = duration)
}


# ============================================================================
# 5. SINGLE-REPLICATE RUNNER + ABC MODEL WRAPPER
# ============================================================================

run_one_sim <- function(args) {
  out <- do.call(branching_process_main, args)
  abc_summarise(out)
}

fiber_abc_model <- function(theta,
                            n_replicates    = N_REPLICATES,
                            include_n_cases = FALSE) {

  R0           <- theta[1]
  prop_funeral <- theta[2]
  p_hcw        <- theta[3]

  args <- build_model_args(R0, prop_funeral, p_hcw)

  reps <- vapply(seq_len(n_replicates),
                 function(i) run_one_sim(args), numeric(4))

  took_off     <- reps["n_deaths", ] >= TAKEOFF_DEATH_THRESHOLD
  takeoff_frac <- mean(took_off)

  if (!any(took_off)) {
    out <- c(takeoff = 0, n_deaths = 0, n_hcw_deaths = 0, duration = 0)
    if (include_n_cases) out <- c(out, n_cases = 0)
    return(out)
  }

  out <- c(takeoff      = takeoff_frac,
           n_deaths     = mean(reps["n_deaths",     took_off]),
           n_hcw_deaths = mean(reps["n_hcw_deaths", took_off]),
           duration     = mean(reps["duration",     took_off]))

  if (include_n_cases) {
    out <- c(out, n_cases = mean(reps["n_cases", took_off]))
  }

  out
}


# ============================================================================
# 6. OBSERVED SUMMARIES (edit to match your real outbreak)
# ============================================================================

observed_summaries <- c(
  takeoff      = 1.0,    # observed outbreak did take off (>= 10 deaths)
  n_deaths     = 11325,
  n_hcw_deaths = 513,
  duration     = 809
)

# ============================================================================
# 7. PRIORS
# ============================================================================

priors <- list(
  c("unif", 1.0, 1.75),    # R0
  c("unif", 0.05, 0.5),    # prop_funeral
  c("unif", 0.0, 0.02)     # prob_hcw_cond_genPop_comm
)


# ============================================================================
# 8. PRIOR PREDICTIVE CHECK -- RUN THIS FIRST
# ============================================================================

prior_predictive_check <- function(n_draws         = 20,
                                   prior_list      = priors,
                                   param_names     = c("R0", "prop_funeral", "p_hcw"),
                                   parallel        = TRUE,
                                   n_replicates    = N_REPLICATES,
                                   include_n_cases = TRUE) {       # NEW

  sample_one <- function(spec, n) {
    dist   <- spec[1]
    params <- as.numeric(spec[-1])
    switch(dist,
           "unif"        = runif(n,  min = params[1], max = params[2]),
           "normal"      = rnorm(n,  mean = params[1], sd = params[2]),
           "lognormal"   = rlnorm(n, meanlog = params[1], sdlog = params[2]),
           "exponential" = rexp(n,   rate = params[1]),
           stop("Unsupported prior distribution: ", dist)
    )
  }

  draws <- as.data.frame(lapply(prior_list, sample_one, n = n_draws))
  names(draws) <- param_names

  theta_list <- lapply(seq_len(nrow(draws)), function(i) as.numeric(draws[i, ]))

  sims_list <- with_progress({
    p <- progressor(steps = length(theta_list))

    fn <- function(theta) {
      out <- fiber_abc_model(theta,
                             n_replicates    = n_replicates,
                             include_n_cases = include_n_cases)
      p()
      out
    }

    if (parallel) {
      future_lapply(theta_list, fn, future.seed = TRUE)
    } else {
      lapply(theta_list, fn)
    }
  })

  sims <- do.call(rbind, sims_list)
  cbind(draws, as.data.frame(sims))
}

set.seed(1)
system.time(pp_par <- prior_predictive_check(20, parallel = TRUE, n_replicates = 5))
set.seed(1)
system.time(pp_ser <- prior_predictive_check(20, parallel = FALSE, n_replicates = 5))


# prior_predictive_check(n_draws = 1000, prior_list = priors)
# set.seed(1)
# pp <- prior_predictive_check(20)
# print(pp)
# summary(pp)


# ============================================================================
# 9. RUN ABC-SMC (Del Moral et al. 2012 adaptive algorithm)
# ============================================================================

result <- ABC_sequential(
  method              = "Delmoral",
  model               = fiber_abc_model,
  prior               = priors,
  nb_simul            = 500,
  summary_stat_target = observed_summaries,
  alpha               = 0.5,
  tolerance_target    = 0.5,
  M                   = 1,
  p_acc_min           = 0.03,
  use_seed            = FALSE,
  verbose             = TRUE,
  n_cluster           = 1                 # parallelism needs source() on workers
)


# ============================================================================
# 10. POSTERIOR INSPECTION
# ============================================================================

posterior <- as.data.frame(result$param)
colnames(posterior) <- c("R0", "prop_funeral", "prob_hcw_comm")

print(apply(posterior, 2, quantile, probs = c(0.025, 0.5, 0.975)))

par(mfrow = c(1, 3))
for (j in seq_len(ncol(posterior))) {
  hist(posterior[, j], breaks = 30, main = colnames(posterior)[j],
       xlab = colnames(posterior)[j])
  abline(v = quantile(posterior[, j], c(0.025, 0.5, 0.975)),
         lty = c(2, 1, 2), col = "red")
}
par(mfrow = c(1, 1))

pairs(posterior, pch = 16, cex = 0.5,
      col = adjustcolor("steelblue", alpha = 0.4))

saveRDS(result,
        file = paste0("fiber_abc_smc_result_", SCENARIO_ID, ".rds"))
