## Add in details on parameter arguments here
## Add in details about outputs etc here
## Basically all the required documentation for this to be
## functional inside a package

## Note: need to add descriptions of each of the function inputs, which are currently missing

branching_process_main <- function(

  ## Transmission
  mn_offspring = NULL,             # DESCRIPTION HERE
  disp_offspring= NULL,            # only used if "nbinom"

  ## Natural history
  generation_time,                 # DESCRIPTION HERE
  infection_to_onset,              # DESCRIPTION HERE

  ## Parameters of the offspring and generation time distributions for general population (genPop)
  mn_offspring_genPop = NULL,               # mean of the offspring distribution for general population
  overdisp_offspring_genPop = NULL,         # overdispersion of the offspring distribution for general population
  Tg_shape_genPop = NULL,                   # gamma shape parameter for Tg distribution for general population
  Tg_rate_genPop = NULL,                    # gamma rate parameter for Tg distribution for general population
  hospital_quarantine_efficacy = NULL,      # efficacy of hospitalisation at reducing transmission (quarantine)

  ## Parameters of the offspring and generation time distributions for HCWs
  mn_offspring_hcw = NULL,                  # mean of the offspring distribution for HCWs
  overdisp_offspring_hcw = NULL,            # overdispersion of the offspring distribution for HCWs
  Tg_shape_hcw = NULL,                      # gamma shape parameter for Tg distribution for HCWs
  Tg_rate_hcw = NULL,                       # gamma rate parameter for Tg distribution for HCWs

  ## Probabilities for genPop infecting either genPop or HCWs, depending on the setting
  prob_hcw_cond_genPop_comm = NULL,         # prob that a community-located infection generated by genPop is a HCW
  prob_hcw_cond_genPop_hospital = NULL,      # prob that a hospital-located infection generated by genPop is a HCW

  ## Probabilities for HCW infecting either genPop or HCWs, depending on the setting
  prob_hcw_cond_hcw_comm = NULL,            # prob that a community-located infection generated by HCW is a HCW
  prob_hcw_cond_hcw_hospital = NULL,        # prob that a hospital-located infection generated by HCW is a HCW

  ## Setting model for HCWs
  prob_hospital_cond_hcw_preAdm = NULL,     # probability that an infection generated prior to parent hospitaliation occurs in the hospital (whilst HCW is working)
  ppe_efficacy_hcw = NULL,                  # efficacy of PPE/IPC measures at reducing transmission (i.e. pre hospitalisation)
  hospital_quarantine_efficacy = NULL,      # efficacy of quarantine at reducing transmission (i.e. post hospitalisation)

  ## Funeral occurrence
  p_unsafe_funeral_comm = NULL, ## probability the parent had an unsafe funeral Cond. on a community death
  p_unsafe_funeral_hosp = NULL, ## probability parent had an unsafe funeral cond. on a hospital death

  ## Offspring distribution for unsafe funeral event
  mn_offspring_funeral = NULL, # mean number of offspring at unsafe funeral
  overdisp_offspring_funeral = NULL, # overdispersion of the above number of offspring

  ## Timing of funeral infections (delay after outcome)
  Tg_shape_funeral = NULL, # gamma shape parameter for Tg distribution at funerals ### have high shape, high rate to get low variance ##
  Tg_rate_funeral = NULL,  #gamma rate parameter for Tg distribution at funerals

  ## HCW vs genPop at funeral ## NOTE- THIS NEEDS TO BE TWO INPUTS BASED ON WHETHER INFECTOR IS HCW OR GENPOP - JACOB STILL ADDING
  prob_hcw_cond_funeral = NULL, ### probability that the unsafe funeral infector infects a HCW

  ## Misc
  t0 = 0,
  tf = Inf,
  population,
  check_final_size,
  initial_immune = 0,
  seeding_cases,
  seed
) {

  ## Set seed for reproducibility
  set.seed(seed)

  ## Initialise the susceptible population
  susc <- population - initial_immune

  ## Offspring distribution
  ### NOTE: REVISIT THIS LATER ON - NOT CLEAR TO ME WHETHER WE SHOULD BE DOING THIS OR NOT.
  if (disp_offspring <= 1) {
    stop("For 'nbinom', require disp_offspring > 1 (use 'pois' otherwise).")
  }
  offspring_fun <- function(n, susc) {
    new_mn <- mn_offspring * susc / population
    size <- new_mn / (disp_offspring - 1)
    truncdist::rtrunc(n, spec = "nbinom", b = susc, mu = new_mn, size = size)
  }

  ## Preallocate data frame -
  max_cases <- check_final_size
  tdf <- data.frame(
    id                           = integer(max_cases),   # id of the infected individual
    class                        = NA_character_,
    parent                       = integer(max_cases),   # ancestor of the infected individual i.e. the parent
    parent_class                 = NA_character_,
    generation                   = integer(max_cases),   # generation of the infected individual i.e. how many infections precede them in the transmission chain
    time_infection_relative      = NA_real_,             # time of the infection relative to the parent
    time_infection_absolute      = NA_real_,             # time of the infection in absolute calendar time (i.e. since start of outbreak)

    symptomatic                  = NA,                   # are they symptomatic?
    time_symptom_onset_relative  = NA_real_,             # time of symptom onset relative to the parent
    time_symptom_onset_absolute  = NA_real_,             # time of symptom onset in absolute calendar time (i.e. since start of outbreak)

    hospitalisation              = ,
    time_hospitalisation_relative        = ,
    time_hospitalisation_absolute        = ,

    outcome                      = NA_character_,         # what the outcome is for that individual
    time_outcome_relative        = ,
    time_outcome_absolute        = ,

    funeral_safety               = NA_character_,
    time_funeral_relative        = ,
    time_funeral_absolute        = ,

    n_offspring                  = integer(max_cases),
    offspring_generated           = FALSE,
    stringsAsFactors = FALSE
  )

  ## Seed cases
  tdf[1:seeding_cases, ] <- data.frame(
    id              = seq_len(seeding_cases),
    ancestor        = NA_integer_,
    generation      = 1L,
    time_infection  = t0 + seq(from = 0, to = 0.01, length.out = seeding_cases),
    time_onset      = NA_real_,
    n_offspring     = NA_integer_,
    offspring_generated = FALSE,
    stringsAsFactors = FALSE
  )

  ## Main expansion loop
  while ( any(is.na(tdf$n_offspring)) && susc > 0 ) {

    ## Get earliest infection not yet expanded
    time_infection_index <- min(tdf$time_infection[!tdf$offspring_generated & !is.na(tdf$time_infection)])
    idx <- which(tdf$time_infection == time_infection_index & !tdf$offspring_generated)[1]

    id_index   <- tdf$id[idx]
    t_index    <- tdf$time_infection[idx]
    gen_index  <- tdf$generation[idx]
    current_max <- max(tdf$id, na.rm = TRUE)

    ## Natural history timing
    tdf$time_onset[idx] <- infection_to_onset(1)

    ## Draw offspring count
    ## Note: This is just an example, but imagine I'm not sure that offspring function is working correctly;
    ##        I'll make a note to return to this with something like "I think something weird is going on when
    ##       maybe they're a healthcare worker?"
    n_off <- offspring_fun(1, susc)
    tdf$n_offspring[idx] <- n_off
    tdf$offspring_generated[idx] <- TRUE

    ## If children exist, append them
    if (n_off > 0) {
      # stop if we’d exceed preallocated size
      if ((current_max + n_off) > max_cases)
        n_off <- max(0L, max_cases - current_max)

      if (n_off > 0) {
        new_ids   <- current_max + seq_len(n_off)
        new_times <- t_index + generation_time(n_off)

        rows <- new_ids
        tdf[rows, "id"]             <- new_ids
        tdf[rows, "ancestor"]       <- id_index
        tdf[rows, "generation"]     <- gen_index + 1L
        tdf[rows, "time_infection"] <- new_times
        tdf[rows, "time_onset"]     <- NA_real_
        tdf[rows, "n_offspring"]    <- NA_integer_
        tdf[rows, "offspring_generated"] <- FALSE
      }
    }

    ## Deplete susceptibles
    susc <- susc - tdf$n_offspring[idx]

    ## Optional: hard stop if we filled the table
    if (max(tdf$id, na.rm = TRUE) >= max_cases) break
  }

  ## Final tidy
  tdf <- tdf[!is.na(tdf$time_infection) & tdf$time_infection <= tf, ]
  tdf <- tdf[order(tdf$time_infection, tdf$id), ]
  tdf$offspring_generated <- NULL
  rownames(tdf) <- NULL
  tdf
}

