
implement_quarantine <- function(symptom_onset_time,            # time after infection that the index infection develops symptoms
                                 quarantine_time,               # time after symptom onset that the index infection quarantines
                                 n_offspring,                   # number of offspring associated with the index infection
                                 offspring_infection_times,     # timings (relative to index infection time) of infections of secondary offspring
                                 offspring_function_draw,       # characteristics of the secondary offspring generated by the index infection
                                 quarantine_efficacy) {         # efficacy of quarantining at preventing household infections

  ## Check offspring infection times relative to time of quarantining (i.e. do they otherwise occur before or after quarantining)
  ##  1 = quarantine can avert this infection, 0 is the infection occurs before quarantining
  quarantine_possible_avert <- ifelse((symptom_onset_time + quarantine_time) < offspring_infection_times, 1, 0)  # Only if an infection occurs later than quarantining can it be averted by quarantine

  ## Implementing quarantining and identifying the infections NOT prevented by quarantining (i.e. those to retain = 1, those averted = 0)
  offspring_quarantine_retained <- rbinom(n = n_offspring, size = 1, prob = 1 - (quarantine_possible_avert * quarantine_efficacy))
  offspring_quarantine_retained_index <- which(offspring_quarantine_retained == 1)
  offspring_quarantine_averted_index <- which(offspring_quarantine_retained == 0)

  # Updating index_n_offspring and secondary_infection_times in light of new removals due to quarantining
  n_offspring <- sum(offspring_quarantine_retained)                                                       # accounting for infections averted by quarantine from index_n_offspring
  infection_times <- offspring_infection_times[offspring_quarantine_retained_index]                       # removing infections averted by quarantine from secondary_infection_times

  ## Returning the number of offspring, offspring infection times and characteristics after removing infections averted by quarantining
  return(list(updated_n_offspring = n_offspring,
              updated_infection_times = infection_times))

}

