offspring_function_hcw <- function(

  ## Characteristics and properties of the parent (who we are generating the offspring for)
  parent_hospitalised = NULL,               # whether the parent (HCW infector) is hospitalised or not
  parent_time_to_hospitalisation = NULL,    # if hospitalised, the time of hospitalisation (relative to infection)
  parent_time_to_outcome = NULL,            # the time when the parent dies/recovers (relative to infection)

  ## Parameters of the offspring and generation time distributions for HCWs
  mn_offspring_hcw = NULL,                  # mean of the offspring distribution for HCWs
  overdisp_offspring_hcw = NULL,            # overdispersion of the offspring distribution for HCWs
  Tg_shape_hcw = NULL,                      # gamma shape parameter for Tg distribution for HCWs
  Tg_rate_hcw = NULL,                       # gamma rate parameter for Tg distribution for HCWs

  ## Setting model for HCWs
  p_pre_hosp_worker = NULL,                 # Pr(pre-admission event occurs in hospital while working)
  ppe_efficacy_worker = NULL,               # reduction for pre-admission hospital (worker PPE/IPC), in [0,1]
  hospital_quarantine_efficacy = NULL,      # reduction for post-admission hospital (quarantine), in [0,1]

  ## Probabilities for HCW infecting either genPop or HCWs, depending on the setting
  prob_hcw_cond_hcw_comm = NULL,            # prob that a community-located infection generated by HCW is a HCW
  prob_hcw_cond_hcw_hospital = NULL         # prob that a hospital-located infection generated by HCW is a HCW
) {

  #########################################################################################
  ## Checks to make sure function inputs are correctly specified
  #########################################################################################
  if (is.null(parent_hospitalised) || length(parent_hospitalised) != 1L || !is.logical(parent_hospitalised) || is.na(parent_hospitalised)) {
    stop("`parent_hospitalised` must be a single logical value: TRUE or FALSE.", call. = FALSE)
  }
  if (isTRUE(parent_hospitalised)) {
    if (is.null(parent_time_to_hospitalisation) || length(parent_time_to_hospitalisation) != 1L ||
        !is.numeric(parent_time_to_hospitalisation) || is.na(parent_time_to_hospitalisation) || parent_time_to_hospitalisation < 0) {
      stop("When `parent_hospitalised` is TRUE, `parent_time_to_hospitalisation` must be a single non-negative numeric value (not NA).", call. = FALSE)
    }
  }
  if (is.null(parent_time_to_outcome) || length(parent_time_to_outcome) != 1L ||
      !is.numeric(parent_time_to_outcome) || is.na(parent_time_to_outcome) || parent_time_to_outcome < 0) {
    stop("`parent_time_to_outcome` must be a single non-negative numeric value (not NA).", call. = FALSE)
  }
  if (identical(parent_hospitalised, FALSE)) {
    if (!is.na(parent_time_to_hospitalisation)) {
      stop("When `parent_hospitalised` is FALSE, `parent_time_to_hospitalisation` must be NA.", call. = FALSE)
    }
  }

  ## Parameter checks (positivity / bounds)
  for (nm in c("mn_offspring_hcw","overdisp_offspring_hcw","Tg_shape_hcw","Tg_rate_hcw")) {
    val <- get(nm, inherits = FALSE)
    if (is.null(val) || length(val) != 1L || !is.numeric(val) || is.na(val) || val <= 0)
      stop(sprintf("`%s` must be a single positive numeric value.", nm), call. = FALSE)
  }
  for (nm in c("p_pre_hosp_worker","ppe_efficacy_worker","hospital_quarantine_efficacy",
               "prob_hcw_cond_hcw_comm","prob_hcw_cond_hcw_hospital")) {
    val <- get(nm, inherits = FALSE)
    if (is.null(val) || length(val) != 1L || !is.numeric(val) || is.na(val) || val < 0 || val > 1)
      stop(sprintf("`%s` must be a single numeric value in [0, 1].", nm), call. = FALSE)
  }

  ########################################################################################################
  ## Generating offspring, offspring infection times, offspring infection locations & offspring classes
  ########################################################################################################

  # Step 1: Draw from offspring distribution to produce raw number of offspring
  num_offspring_raw <- rnbinom(n = 1, mu = mn_offspring_hcw, size = overdisp_offspring_hcw)
  if (num_offspring_raw == 0) {
    return(data.frame(
      id = integer(0),
      parent_class = character(0),
      setting = character(0),
      time_infection = numeric(0),
      class = character(0),
      stringsAsFactors = FALSE
    ))
  }

  # Step 2: Generate time of infection for each offspring based on the generation time (truncated at outcome)
  infection_times <- rtrunc_gamma(
    n = num_offspring_raw, lower = 0, upper = parent_time_to_outcome,
    Tg_shape = Tg_shape_hcw, Tg_rate = Tg_rate_hcw
  )

  # Step 3: Generate location of infection for HCW parents
  #         - Pre-admission events can be hospital *or* community (while working), via p_pre_hosp_worker
  #         - Post-admission events are necessarily hospital
  t_hosp <- if (isTRUE(parent_hospitalised)) parent_time_to_hospitalisation else Inf
  if (is.finite(t_hosp) && parent_time_to_outcome <= t_hosp) t_hosp <- Inf

  pre_admission <- infection_times < t_hosp
  is_hosp_pre <- as.logical(rbinom(n = length(infection_times), size = 1, prob = p_pre_hosp_worker))
  infection_settings <- ifelse(pre_admission,
                               ifelse(is_hosp_pre, "hospital", "community"),
                               "hospital")

  # Step 4: Thin / remove some hospital infections due to PPE (pre-adm) or quarantine (post-adm)
  p_keep_infection <- ifelse(
    infection_settings == "community",
    1,
    ifelse(pre_admission, 1 - ppe_efficacy_worker, 1 - hospital_quarantine_efficacy)
  )
  keep_infection <- as.logical(rbinom(n = length(infection_times), size = 1, prob = p_keep_infection))
  infection_times <- infection_times[keep_infection]
  infection_settings <- infection_settings[keep_infection]
  num_offspring_quarantine <- length(infection_times)

  # Step 5: Assign class (HCW or genPop) to each offspring based on setting (HCW parent)
  offspring_class <- rep("genPop", num_offspring_quarantine)
  prob_hcw <- ifelse(infection_settings == "community",
                     prob_hcw_cond_hcw_comm,
                     prob_hcw_cond_hcw_hospital)
  flip_hcw <- as.logical(rbinom(n = num_offspring_quarantine, size = 1, prob = prob_hcw))
  offspring_class[flip_hcw] <- "HCW"

  # Step 6: Define and output dataframe with the results
  offspring_df <- data.frame(
    id = seq_len(num_offspring_quarantine),
    parent_class = rep("HCW", num_offspring_quarantine),
    setting = infection_settings,
    time_infection = infection_times,
    class = offspring_class,
    stringsAsFactors = FALSE
  )

  return(offspring_df)
}
