#' Generate offspring for a general-population (genPop) parent with time-based setting and hospital thinning
#'
#' Simulates secondary infections (offspring) generated by a **general-population** parent.
#' The number of candidate offspring is drawn from a Negative Binomial distribution.
#' Candidate infection times are drawn from a **truncated Gamma** generation-time distribution
#' on \eqn{[0, t_\mathrm{outcome}]}. Each event is assigned a setting by comparing the infection
#' time to the parent's hospitalisation time: events before admission are labelled
#' \code{"community"} and those after admission \code{"hospital"}. A hospital “quarantine”
#' effect then thins post-admission hospital events with keep-probability
#' \eqn{1 - \mathrm{hospital\_quarantine\_efficacy}(t)}. By default,
#' \code{hospital_quarantine_efficacy(t)} is calculated internally from ETU/ETC coverage,
#' IPC maturity, and baseline ETU efficacy at each candidate hospital transmission time.
#' A direct scalar or time-varying \code{hospital_quarantine_efficacy} can still be supplied
#' for backwards compatibility.
#' Finally, each offspring is assigned a class (\code{"HCW"} or \code{"genPop"}) using
#' setting-specific probabilities.
#'
#' @param parent_info One-row data.frame/list containing parent infection, hospitalisation and outcome times.
#' @param mn_offspring_genPop Positive numeric. Mean of the Negative Binomial offspring distribution
#'   for genPop parents (\code{rnbinom(mu = ..., size = ...)}).
#' @param overdisp_offspring_genPop Positive numeric. Negative Binomial \code{size} (overdispersion)
#'   for genPop parents.
#' @param Tg_shape_genPop Positive numeric. Shape of the Gamma generation-time distribution
#'   for genPop parents (before truncation).
#' @param Tg_rate_genPop Positive numeric. Rate of the Gamma generation-time distribution
#'   for genPop parents (before truncation). Mean GT is \code{Tg_shape_genPop / Tg_rate_genPop}.
#' @param hospital_quarantine_efficacy Optional numeric in \code{[0,1]} or function(t). Direct
#'   effective hospital admission/ETU/quarantine efficacy at reducing post-admission transmission.
#'   If supplied, this is used directly and resolved at the absolute calendar time of each
#'   candidate hospital infection. If \code{NULL}, efficacy is calculated from \code{prop_etu},
#'   \code{ipc_helper}, and \code{etu_efficacy_baseline}.
#' @param prop_etu Numeric in \code{[0,1]} or function(t). Proportion of hospitalised cases managed
#'   in ETU/ETC care at time \code{t}; used when \code{hospital_quarantine_efficacy = NULL}.
#' @param ipc_helper Numeric in \code{[0,1]} or function(t). Time-varying IPC/response maturity
#'   proxy at time \code{t}; used when \code{hospital_quarantine_efficacy = NULL}.
#' @param etu_efficacy_baseline Numeric between 0 and 1. Baseline transmission-blocking efficacy
#'   of ETU/ETC care before additional IPC maturity improvements; used when
#'   \code{hospital_quarantine_efficacy = NULL}.
#' @param prob_hcw_cond_genPop_comm Numeric in \code{[0,1]}. Probability that a community-located
#'   offspring generated by a genPop parent is an HCW.
#' @param prob_hcw_cond_genPop_hospital Numeric in \code{[0,1]}. Probability that a hospital-located
#'   offspring generated by a genPop parent is an HCW.
#' @export
offspring_function_genPop <- function(

  ## Characteristics and properties of the parent (who we are generating the offspring for)
  parent_info,

  ## Parameters of the offspring and generation time distributions for general population (genPop)
  mn_offspring_genPop = NULL,               # mean of the offspring distribution for general population
  overdisp_offspring_genPop = NULL,         # overdispersion of the offspring distribution for general population
  Tg_shape_genPop = NULL,                   # gamma shape parameter for Tg distribution for general population
  Tg_rate_genPop = NULL,                    # gamma rate parameter for Tg distribution for general population
  hospital_quarantine_efficacy = NULL,      # optional scalar/function(t): direct hospital efficacy, retained for backwards compatibility
  prop_etu = NULL,                          # scalar/function(t): proportion of hospitalised cases in ETU/ETC care
  ipc_helper = NULL,                        # scalar/function(t): IPC/response maturity proxy
  etu_efficacy_baseline = NULL,             # scalar: baseline ETU/ETC efficacy before IPC maturity adjustment

  ## Probabilities for genPop infecting either genPop or HCWs, depending on the setting
  prob_hcw_cond_genPop_comm = NULL,         # prob that a community-located infection generated by genPop is a HCW
  prob_hcw_cond_genPop_hospital = NULL      # prob that a hospital-located infection generated by genPop is a HCW
) {

  ## Local helpers for parameters that can be either scalars or functions of
  ## absolute calendar time. The actual interpolation is handled by
  ## resolve_time_varying(), so this function stays scenario-agnostic.
  validate_probability_or_time_varying <- function(param, param_name) {
    if (is.function(param)) {
      return(invisible(NULL))
    }
    if (!is.numeric(param) || length(param) != 1L || is.na(param) || param < 0 || param > 1) {
      stop(sprintf("`%s` must be a function(t) or a single numeric in [0, 1].", param_name),
           call. = FALSE)
    }
    invisible(NULL)
  }

  validate_probability_scalar <- function(param, param_name) {
    if (!is.numeric(param) || length(param) != 1L || is.na(param) || param < 0 || param > 1) {
      stop(sprintf("`%s` must be a single numeric in [0, 1].", param_name),
           call. = FALSE)
    }
    invisible(NULL)
  }

  resolve_probability <- function(param, t, param_name) {
    value <- resolve_time_varying(param = param, t = t, param_name = param_name)
    if (any(value < 0 | value > 1)) {
      stop(sprintf("`%s` must resolve to value(s) in [0, 1].", param_name), call. = FALSE)
    }
    value
  }

  resolve_hospital_quarantine_efficacy <- function(t) {
    if (!is.null(hospital_quarantine_efficacy)) {
      return(resolve_probability(
        hospital_quarantine_efficacy,
        t,
        "hospital_quarantine_efficacy"
      ))
    }

    prop_etu_t <- resolve_probability(prop_etu, t, "prop_etu")
    ipc_helper_t <- resolve_probability(ipc_helper, t, "ipc_helper")

    etu_efficacy_at_t <-
      etu_efficacy_baseline +
      (1 - etu_efficacy_baseline) * ipc_helper_t

    hospital_quarantine_efficacy_t <-
      prop_etu_t * etu_efficacy_at_t +
      (1 - prop_etu_t) * ipc_helper_t

    pmin(pmax(hospital_quarantine_efficacy_t, 0), 1)
  }

  # Step 0: Extract relevant parent information from parent_info
  parent_hospitalised = parent_info$hospitalisation                          # whether the parent (infector) is hospitalised or not
  parent_time_to_hospitalisation = parent_info$time_hospitalisation_relative # if parent is hospitalised, the time of hospitalisation (relative to infection)
  parent_time_to_outcome = parent_info$time_outcome_relative                 # the time when the parent dies/recovers (relative to time of infection)
  parent_time_infection_absolute = parent_info$time_infection_absolute       # absolute calendar time of parent infection

  #########################################################################################
  ## Checks to make sure function inputs are correctly specified
  #########################################################################################
  if (is.null(parent_hospitalised) || length(parent_hospitalised) != 1L || !is.logical(parent_hospitalised) || is.na(parent_hospitalised)) {
    stop("`parent_hospitalised` must be a single logical value: TRUE or FALSE.", call. = FALSE)
  }
  if (isTRUE(parent_hospitalised)) {
    if (is.null(parent_time_to_hospitalisation) || length(parent_time_to_hospitalisation) != 1L ||
        !is.numeric(parent_time_to_hospitalisation) || is.na(parent_time_to_hospitalisation) || parent_time_to_hospitalisation < 0) {
      stop("When `parent_hospitalised` is TRUE, `parent_time_to_hospitalisation` must be a single non-negative numeric value (not NA).", call. = FALSE)
    }
  }
  if (is.null(parent_time_to_outcome) || length(parent_time_to_outcome) != 1L ||
      !is.numeric(parent_time_to_outcome) || is.na(parent_time_to_outcome) || parent_time_to_outcome < 0) {
    stop("`parent_time_to_outcome` must be a single non-negative numeric value (not NA).", call. = FALSE)
  }
  if (is.null(parent_time_infection_absolute) || length(parent_time_infection_absolute) != 1L ||
      !is.numeric(parent_time_infection_absolute) || is.na(parent_time_infection_absolute)) {
    stop("`parent_info$time_infection_absolute` must be a single non-missing numeric value.", call. = FALSE)
  }
  if (identical(parent_hospitalised, FALSE)) {
    if (!is.na(parent_time_to_hospitalisation)) {
      stop("When `parent_hospitalised` is FALSE, `parent_time_to_hospitalisation` must be NA.", call. = FALSE)
    }
  }

  ## Parameter checks (positivity / bounds)
  for (nm in c("mn_offspring_genPop", "overdisp_offspring_genPop", "Tg_shape_genPop", "Tg_rate_genPop")) {
    val <- get(nm, inherits = FALSE)
    if (is.null(val) || length(val) != 1L || !is.numeric(val) || is.na(val) || val <= 0) {
      stop(sprintf("`%s` must be a single positive numeric value.", nm), call. = FALSE)
    }
  }
  for (nm in c("prob_hcw_cond_genPop_comm", "prob_hcw_cond_genPop_hospital")) {
    val <- get(nm, inherits = FALSE)
    if (is.null(val) || length(val) != 1L || !is.numeric(val) || is.na(val) || val < 0 || val > 1) {
      stop(sprintf("`%s` must be a single numeric value in [0, 1].", nm), call. = FALSE)
    }
  }
  if (!is.null(hospital_quarantine_efficacy)) {
    validate_probability_or_time_varying(hospital_quarantine_efficacy, "hospital_quarantine_efficacy")
  } else {
    validate_probability_or_time_varying(prop_etu, "prop_etu")
    validate_probability_or_time_varying(ipc_helper, "ipc_helper")
    validate_probability_scalar(etu_efficacy_baseline, "etu_efficacy_baseline")
  }

  ########################################################################################################
  ## Generating offspring, offspring infection times, offspring infection locations & offspring classes
  ########################################################################################################

  # Step 1: Draw from offspring distribution to produce raw number of offspring
  num_offspring_raw <- rnbinom(n = 1, mu = mn_offspring_genPop, size = overdisp_offspring_genPop)

  if (num_offspring_raw == 0L) {
    return(data.frame(infection_location = character(0),
                      time_infection_relative = numeric(0),
                      class = character(0),
                      stringsAsFactors = FALSE))
  }

  # Step 2: Generate time of infection for each offspring based on the generation time
  infection_times <- rtrunc_gamma(n = num_offspring_raw,
                                  lower = 0,
                                  upper = parent_time_to_outcome,
                                  Tg_shape = Tg_shape_genPop,
                                  Tg_rate = Tg_rate_genPop)
  infection_times_absolute <- parent_time_infection_absolute + infection_times

  # Step 3: Generate location of infection depending on i) whether parent is hospitalised and ii) if hospitalised, the time
  #         of hospitalisation relative to time of infection
  t_hosp <- if (isTRUE(parent_hospitalised)) parent_time_to_hospitalisation else Inf
  if (is.finite(t_hosp) && parent_time_to_outcome <= t_hosp) t_hosp <- Inf
  infection_settings <- ifelse(infection_times < t_hosp, "community", "hospital")

  # Step 4: Thin / remove some hospital infections due to quarantining effect / similar.
  #         Hospital quarantine efficacy is resolved at the absolute calendar
  #         time of each candidate hospital transmission. If a direct
  #         hospital_quarantine_efficacy is supplied, it is used directly.
  #         Otherwise, it is calculated from prop_etu(t), ipc_helper(t), and
  #         etu_efficacy_baseline:
  #           etu_efficacy(t) = etu_efficacy_baseline +
  #             (1 - etu_efficacy_baseline) * ipc_helper(t)
  #           hospital_quarantine_efficacy(t) =
  #             prop_etu(t) * etu_efficacy(t) +
  #             (1 - prop_etu(t)) * ipc_helper(t)
  p_keep_infection <- rep(1, length(infection_times))
  hospital_candidates <- infection_settings == "hospital"
  if (any(hospital_candidates)) {
    hospital_quarantine_efficacy_t <- resolve_hospital_quarantine_efficacy(
      infection_times_absolute[hospital_candidates]
    )
    p_keep_infection[hospital_candidates] <- 1 - hospital_quarantine_efficacy_t
  }

  keep_infection <- as.logical(rbinom(n = length(infection_times), size = 1, prob = p_keep_infection))
  infection_times <- infection_times[keep_infection]
  infection_settings <- infection_settings[keep_infection]
  num_offspring_quarantine <- sum(keep_infection)

  # Step 5: Assign class (HCW or genPop) to each offspring based on i) identity of parent and ii) location of infection
  offspring_class <- rep("genPop", length(infection_times))
  prob_hcw <- ifelse(infection_settings == "community", prob_hcw_cond_genPop_comm, prob_hcw_cond_genPop_hospital)
  flip_hcw <- as.logical(rbinom(n = length(infection_times), size = 1, prob = prob_hcw))
  offspring_class[flip_hcw] <- "HCW"

  # Step 6: Define and output dataframe with the results
  offspring_df <- data.frame(infection_location = infection_settings,
                             time_infection_relative = infection_times,
                             class = offspring_class,
                             stringsAsFactors = FALSE)
  return(offspring_df)
}
