#' Generate offspring for a healthcare-worker (HCW) parent with work-place and post-admission thinning
#'
#' Simulates secondary infections (offspring) generated by a **healthcare-worker** parent.
#' The number of candidate offspring is drawn from a Negative Binomial distribution.
#' Candidate infection times are drawn from a **truncated Gamma** generation-time distribution
#' on \eqn{[0, t_\mathrm{outcome}]}. For HCW parents, **pre-admission** candidate infections
#' may occur in the **hospital** (while working) or in the **community**: each pre-admission
#' event is assigned to the hospital with probability \code{prob_hospital_cond_hcw_preAdm}
#' and to the community otherwise. Candidate events occurring at or after the parent's
#' hospitalisation time are always labelled \code{"hospital"}. Hospital-setting events are then
#' thinned to reflect protection before admission (PPE/IPC) and quarantine after admission.
#' Pre-admission PPE/IPC efficacy is resolved at the absolute calendar time of each candidate
#' pre-admission hospital transmission event. Post-admission hospital quarantine efficacy is
#' resolved at candidate hospital transmission times and can either be supplied directly or
#' calculated internally from ETU/ETC coverage, IPC maturity, and baseline ETU efficacy.
#' Finally, each offspring is assigned a class (\code{"HCW"} or \code{"genPop"}) using setting-specific probabilities.
#'
#' @param parent_info One-row data.frame/list containing parent infection, hospitalisation and outcome times.
#' @param mn_offspring_hcw Positive numeric. Mean of the Negative Binomial offspring distribution
#'   for HCW parents (\code{rnbinom(mu = ..., size = ...)}).
#' @param overdisp_offspring_hcw Positive numeric. Negative Binomial \code{size} (overdispersion)
#'   for HCW parents.
#' @param Tg_shape_hcw Positive numeric. Shape of the Gamma generation-time distribution
#'   for HCW parents (before truncation).
#' @param Tg_rate_hcw Positive numeric. Rate of the Gamma generation-time distribution
#'   for HCW parents (before truncation). Mean GT is \code{Tg_shape_hcw / Tg_rate_hcw}.
#' @param prob_hospital_cond_hcw_preAdm Numeric in \code{[0,1]}. Probability that a pre-admission
#'   candidate infection occurs in the hospital setting while the HCW is working.
#' @param ppe_efficacy_hcw Numeric in \code{[0,1]} or function(t). Efficacy of PPE/IPC at reducing
#'   pre-admission hospital transmission. If a function, it is resolved at the absolute calendar
#'   time of each candidate pre-admission hospital infection.
#' @param hospital_quarantine_efficacy Optional numeric in \code{[0,1]} or function(t). Direct
#'   effective hospital admission/ETU/quarantine efficacy at reducing post-admission hospital
#'   transmission. If supplied, this is used directly and resolved at the absolute calendar time
#'   of each candidate post-admission hospital infection. If \code{NULL}, efficacy is calculated
#'   from \code{prop_etu}, \code{ipc_helper}, and \code{etu_efficacy_baseline}.
#' @param prop_etu Numeric in \code{[0,1]} or function(t). Proportion of hospitalised cases managed
#'   in ETU/ETC care at time \code{t}; used when \code{hospital_quarantine_efficacy = NULL}.
#' @param ipc_helper Numeric in \code{[0,1]} or function(t). Time-varying IPC/response maturity
#'   proxy at time \code{t}; used when \code{hospital_quarantine_efficacy = NULL}.
#' @param etu_efficacy_baseline Numeric between 0 and 1. Baseline transmission-blocking efficacy
#'   of ETU/ETC care before additional IPC maturity improvements; used when
#'   \code{hospital_quarantine_efficacy = NULL}.
#' @param obv_pep_enabled Logical scalar. If TRUE, applies an OBV PEP infection-prevention
#'   gate to eligible candidate HCW exposures after existing IPC/PPE and ETU/quarantine thinning.
#' @param obv_pep_coverage_hcw Numeric in \code{[0,1]} or function(t). Probability an eligible
#'   HCW exposure receives OBV PEP at calendar time \code{t}.
#' @param obv_pep_adherence Numeric in \code{[0,1]} or function(t). Probability an OBV recipient
#'   adheres sufficiently for efficacy to apply.
#' @param obv_pep_dpc Non-negative numeric or function(t). Days post challenge/exposure to first
#'   dose. The simplest working assumption is \code{obv_pep_dpc = 1}.
#' @param obv_pep_efficacy NULL, numeric in \code{[0,1]}, or function(dpc). If NULL, uses
#'   \code{obv_pep_efficacy_from_dpc()}, which is cut to zero after 10 DPC.
#' @param obv_pep_target_locations Character vector of exposure settings eligible for OBV PEP.
#'   Defaults to \code{"hospital"} for HCW PEP.
#' @param prob_hcw_cond_hcw_comm Numeric in \code{[0,1]}. Probability that a community-located
#'   offspring generated by an HCW parent is an HCW.
#' @param prob_hcw_cond_hcw_hospital Numeric in \code{[0,1]}. Probability that a hospital-located
#'   offspring generated by an HCW parent is an HCW.
#' @export
offspring_function_hcw <- function(

  ## Characteristics and properties of the parent (who we are generating the offspring for)
  parent_info,

  ## Parameters of the offspring and generation time distributions for HCWs
  mn_offspring_hcw = NULL,                  # mean of the offspring distribution for HCWs
  overdisp_offspring_hcw = NULL,            # overdispersion of the offspring distribution for HCWs
  Tg_shape_hcw = NULL,                      # gamma shape parameter for Tg distribution for HCWs
  Tg_rate_hcw = NULL,                       # gamma rate parameter for Tg distribution for HCWs

  ## Setting model for HCWs
  prob_hospital_cond_hcw_preAdm = NULL,     # probability that an infection generated prior to parent hospitaliation occurs in the hospital (whilst HCW is working)
  ppe_efficacy_hcw = NULL,                  # scalar or function(t): PPE/IPC efficacy for pre-admission hospital transmission
  hospital_quarantine_efficacy = NULL,      # optional scalar/function(t): direct hospital efficacy, retained for backwards compatibility
  prop_etu = NULL,                          # scalar/function(t): proportion of hospitalised cases in ETU/ETC care
  ipc_helper = NULL,                        # scalar/function(t): IPC/response maturity proxy
  etu_efficacy_baseline = NULL,             # scalar: baseline ETU/ETC efficacy before IPC maturity adjustment

  ## Obeldesivir PEP for exposed HCWs
  obv_pep_enabled = FALSE,
  obv_pep_coverage_hcw = 0,
  obv_pep_adherence = 1,
  obv_pep_dpc = 1,
  obv_pep_efficacy = NULL,
  obv_pep_target_locations = "hospital",

  ## Probabilities for HCW infecting either genPop or HCWs, depending on the setting
  prob_hcw_cond_hcw_comm = NULL,            # prob that a community-located infection generated by HCW is a HCW
  prob_hcw_cond_hcw_hospital = NULL         # prob that a hospital-located infection generated by HCW is a HCW
) {

  ## Local helpers for parameters that can be either scalars or functions of
  ## absolute calendar time. The actual interpolation is handled by
  ## resolve_time_varying(), so this function stays scenario-agnostic.
  validate_probability_or_time_varying <- function(param, param_name) {
    if (is.function(param)) {
      return(invisible(NULL))
    }
    if (!is.numeric(param) || length(param) != 1L || is.na(param) || param < 0 || param > 1) {
      stop(sprintf("`%s` must be a function(t) or a single numeric in [0, 1].", param_name),
           call. = FALSE)
    }
    invisible(NULL)
  }

  validate_probability_scalar <- function(param, param_name) {
    if (!is.numeric(param) || length(param) != 1L || is.na(param) || param < 0 || param > 1) {
      stop(sprintf("`%s` must be a single numeric in [0, 1].", param_name),
           call. = FALSE)
    }
    invisible(NULL)
  }

  resolve_probability <- function(param, t, param_name) {
    value <- resolve_time_varying(param = param, t = t, param_name = param_name)
    if (any(value < 0 | value > 1)) {
      stop(sprintf("`%s` must resolve to value(s) in [0, 1].", param_name), call. = FALSE)
    }
    value
  }

  resolve_hospital_quarantine_efficacy <- function(t) {
    if (!is.null(hospital_quarantine_efficacy)) {
      return(resolve_probability(
        hospital_quarantine_efficacy,
        t,
        "hospital_quarantine_efficacy"
      ))
    }

    prop_etu_t <- resolve_probability(prop_etu, t, "prop_etu")
    ipc_helper_t <- resolve_probability(ipc_helper, t, "ipc_helper")

    etu_efficacy_at_t <-
      etu_efficacy_baseline +
      (1 - etu_efficacy_baseline) * ipc_helper_t

    if (any(etu_efficacy_at_t < 0 | etu_efficacy_at_t > 1)) {
      stop(
        "`etu_efficacy(t)` must resolve to values between 0 and 1.",
        call. = FALSE
      )
    }

    hospital_quarantine_efficacy_t <-
      prop_etu_t * etu_efficacy_at_t +
      (1 - prop_etu_t) * ipc_helper_t

    if (any(hospital_quarantine_efficacy_t < 0 |
            hospital_quarantine_efficacy_t > 1)) {
      stop(
        "`hospital_quarantine_efficacy(t)` must resolve to values between 0 and 1.",
        call. = FALSE
      )
    }

    hospital_quarantine_efficacy_t
  }

  # Step 0: Extract relevant parent information from parent_info
  parent_hospitalised = parent_info$hospitalisation                          # whether the parent (infector) is hospitalised or not
  parent_time_to_hospitalisation = parent_info$time_hospitalisation_relative # if parent is hospitalised, the time of hospitalisation (relative to infection)
  parent_time_to_outcome = parent_info$time_outcome_relative                 # the time when the parent dies/recovers (relative to time of infection)
  parent_time_infection_absolute = parent_info$time_infection_absolute       # absolute calendar time of parent infection

  #########################################################################################
  ## Checks to make sure function inputs are correctly specified
  #########################################################################################
  if (is.null(parent_hospitalised) || length(parent_hospitalised) != 1L || !is.logical(parent_hospitalised) || is.na(parent_hospitalised)) {
    stop("`parent_hospitalised` must be a single logical value: TRUE or FALSE.", call. = FALSE)
  }
  if (isTRUE(parent_hospitalised)) {
    if (is.null(parent_time_to_hospitalisation) || length(parent_time_to_hospitalisation) != 1L ||
        !is.numeric(parent_time_to_hospitalisation) || is.na(parent_time_to_hospitalisation) || parent_time_to_hospitalisation < 0) {
      stop("When `parent_hospitalised` is TRUE, `parent_time_to_hospitalisation` must be a single non-negative numeric value (not NA).", call. = FALSE)
    }
  }
  if (is.null(parent_time_to_outcome) || length(parent_time_to_outcome) != 1L ||
      !is.numeric(parent_time_to_outcome) || is.na(parent_time_to_outcome) || parent_time_to_outcome < 0) {
    stop("`parent_time_to_outcome` must be a single non-negative numeric value (not NA).", call. = FALSE)
  }
  if (is.null(parent_time_infection_absolute) || length(parent_time_infection_absolute) != 1L ||
      !is.numeric(parent_time_infection_absolute) || is.na(parent_time_infection_absolute)) {
    stop("`parent_info$time_infection_absolute` must be a single non-missing numeric value.", call. = FALSE)
  }
  if (identical(parent_hospitalised, FALSE)) {
    if (!is.na(parent_time_to_hospitalisation)) {
      stop("When `parent_hospitalised` is FALSE, `parent_time_to_hospitalisation` must be NA.", call. = FALSE)
    }
  }

  ## Parameter checks (positivity / bounds)
  for (nm in c("mn_offspring_hcw", "overdisp_offspring_hcw", "Tg_shape_hcw", "Tg_rate_hcw")) {
    val <- get(nm, inherits = FALSE)
    if (is.null(val) || length(val) != 1L || !is.numeric(val) || is.na(val) || val <= 0) {
      stop(sprintf("`%s` must be a single positive numeric value.", nm), call. = FALSE)
    }
  }
  for (nm in c("prob_hospital_cond_hcw_preAdm", "prob_hcw_cond_hcw_comm", "prob_hcw_cond_hcw_hospital")) {
    val <- get(nm, inherits = FALSE)
    if (is.null(val) || length(val) != 1L || !is.numeric(val) || is.na(val) || val < 0 || val > 1) {
      stop(sprintf("`%s` must be a single numeric value in [0, 1].", nm), call. = FALSE)
    }
  }
  validate_probability_or_time_varying(ppe_efficacy_hcw, "ppe_efficacy_hcw")
  if (!is.null(hospital_quarantine_efficacy)) {
    validate_probability_or_time_varying(hospital_quarantine_efficacy, "hospital_quarantine_efficacy")
  } else {
    validate_probability_or_time_varying(prop_etu, "prop_etu")
    validate_probability_or_time_varying(ipc_helper, "ipc_helper")
    validate_probability_scalar(etu_efficacy_baseline, "etu_efficacy_baseline")
  }

  ########################################################################################################
  ## Generating offspring, offspring infection times, offspring infection locations & offspring classes
  ########################################################################################################

  # Step 1: Draw from offspring distribution to produce raw number of offspring
  num_offspring_raw <- rnbinom(n = 1, mu = mn_offspring_hcw, size = overdisp_offspring_hcw)

  if (num_offspring_raw == 0L) {
    return(empty_offspring_dataframe())
  }

  # Step 2: Generate time of infection for each offspring based on the generation time (truncated at outcome)
  infection_times <- rtrunc_gamma(n = num_offspring_raw,
                                  lower = 0,
                                  upper = parent_time_to_outcome,
                                  Tg_shape = Tg_shape_hcw,
                                  Tg_rate = Tg_rate_hcw)
  infection_times_absolute <- parent_time_infection_absolute + infection_times

  # Step 3: Generate location of infection, noting that for HCWs, pre-hospitalisation infections can be community *or* hospital (while working). This is
  #         controlled via prob_hospital_cond_hcw_preAdm. Post-hospitalisation events are necessarily hospital.
  t_hosp <- if (isTRUE(parent_hospitalised)) parent_time_to_hospitalisation else Inf
  if (is.finite(t_hosp) && parent_time_to_outcome <= t_hosp) t_hosp <- Inf
  pre_admission <- infection_times < t_hosp
  is_hosp_pre_admission <- as.logical(rbinom(n = length(infection_times), size = 1, prob = prob_hospital_cond_hcw_preAdm))
  infection_settings <- ifelse(pre_admission, ifelse(is_hosp_pre_admission, "hospital", "community"), "hospital")

  # Step 4: Thin / remove some hospital infections due to PPE (pre-hospitalisation) or quarantine (post-hospitalisation).
  #         Time-varying efficacies are resolved at the absolute calendar time of
  #         each candidate hospital transmission event. Post-admission hospital
  #         quarantine efficacy is either supplied directly or calculated from
  #         prop_etu(t), ipc_helper(t), and etu_efficacy_baseline:
  #           etu_efficacy(t) = etu_efficacy_baseline +
  #             (1 - etu_efficacy_baseline) * ipc_helper(t)
  #           hospital_quarantine_efficacy(t) =
  #             prop_etu(t) * etu_efficacy(t) +
  #             (1 - prop_etu(t)) * ipc_helper(t)
  p_keep_infection <- rep(1, length(infection_times))

  hospital_pre_admission <- infection_settings == "hospital" & pre_admission
  if (any(hospital_pre_admission)) {
    ppe_efficacy_hcw_t <- resolve_probability(
      ppe_efficacy_hcw,
      infection_times_absolute[hospital_pre_admission],
      "ppe_efficacy_hcw"
    )
    p_keep_infection[hospital_pre_admission] <- 1 - ppe_efficacy_hcw_t
  }

  hospital_post_admission <- infection_settings == "hospital" & !pre_admission
  if (any(hospital_post_admission)) {
    hospital_quarantine_efficacy_t <- resolve_hospital_quarantine_efficacy(
      infection_times_absolute[hospital_post_admission]
    )
    p_keep_infection[hospital_post_admission] <- 1 - hospital_quarantine_efficacy_t
  }

  keep_infection <- as.logical(rbinom(n = length(infection_times), size = 1, prob = p_keep_infection))
  infection_times <- infection_times[keep_infection]
  infection_settings <- infection_settings[keep_infection]
  num_offspring_quarantine <- length(infection_times)

  # Step 5: Assign class (HCW or genPop) to each offspring based on setting (HCW parent)
  offspring_class <- rep("genPop", num_offspring_quarantine)
  prob_hcw <- ifelse(infection_settings == "community", prob_hcw_cond_hcw_comm, prob_hcw_cond_hcw_hospital)
  flip_hcw <- as.logical(rbinom(n = num_offspring_quarantine, size = 1, prob = prob_hcw))
  offspring_class[flip_hcw] <- "HCW"

  # Step 6: Apply OBV PEP gate after class assignment. This is deliberately
  #         downstream of PPE/IPC and post-admission quarantine/ETU thinning.
  obv_gate <- apply_obv_pep_gate(
    infection_location = infection_settings,
    offspring_class = offspring_class,
    infection_time_absolute = parent_time_infection_absolute + infection_times,
    obv_pep_enabled = obv_pep_enabled,
    obv_pep_coverage_hcw = obv_pep_coverage_hcw,
    obv_pep_adherence = obv_pep_adherence,
    obv_pep_dpc = obv_pep_dpc,
    obv_pep_efficacy = obv_pep_efficacy,
    obv_pep_target_locations = obv_pep_target_locations
  )

  infection_times <- infection_times[obv_gate$keep]
  infection_settings <- infection_settings[obv_gate$keep]
  offspring_class <- offspring_class[obv_gate$keep]
  obv_metadata <- obv_gate$metadata[obv_gate$keep, , drop = FALSE]

  # Step 7: Define and output dataframe with the results
  offspring_df <- data.frame(infection_location = infection_settings,
                             time_infection_relative = infection_times,
                             class = offspring_class,
                             obv_metadata,
                             stringsAsFactors = FALSE)
  attr(offspring_df, "obv_pep_counts") <- obv_gate$counts

  return(offspring_df)
}
