## Internal utility: resolve a parameter that is either a scalar or a function(t)
## Not exported.
##
## `param` can be either:
##   1. a single numeric value, which is recycled over all requested times; or
##   2. a function of time, usually generated by make_time_varying().
##
## `t` can be a single time or a numeric vector of times. This allows the
## simulation to resolve parameter values for several individuals in one call.
resolve_time_varying <- function(param, t, param_name = "parameter") {

  if (!is.numeric(t)) {
    stop(sprintf("`t` for `%s` must be numeric.", param_name), call. = FALSE)
  }

  if (length(t) == 0L) {
    return(numeric(0))
  }

  if (any(is.na(t))) {
    stop(sprintf("`t` for `%s` contains NA values.", param_name), call. = FALSE)
  }

  param_was_function <- is.function(param)
  if (param_was_function) {
    val <- param(t)
  } else if (is.numeric(param) && length(param) == 1L) {
    val <- rep(param, length(t))
  } else {
    stop(
      sprintf("`%s` must be a single numeric value or a function(t).", param_name),
      call. = FALSE
    )
  }

  if (!is.numeric(val)) {
    stop(sprintf("`%s` evaluated to a non-numeric value.", param_name), call. = FALSE)
  }

  ## Some user-supplied functions return a scalar even when evaluated at
  ## multiple times (a common bug — e.g. using `if (t < x)` instead of
  ## `ifelse`). Warn so the user notices, then recycle to keep the rest
  ## of the pipeline working. Scalar inputs (length(param) == 1) recycle
  ## silently because that is the expected behaviour.
  if (length(val) == 1L && length(t) > 1L) {
    if (param_was_function) {
      warning(
        sprintf(
          "`%s`: function returned a length-1 value when evaluated at %d times; recycling. Check that the function is vectorised over `t`.",
          param_name, length(t)
        ),
        call. = FALSE
      )
    }
    val <- rep(val, length(t))
  }

  if (length(val) != length(t) || any(is.na(val))) {
    stop(
      sprintf("`%s` evaluated to an invalid value at t = %s.",
              param_name, paste(t, collapse = ", ")),
      call. = FALSE
    )
  }

  return(as.numeric(val))
}
